// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgwzTp5qH-iSVU3XK9tqGXt2DnjllDRes',
    appId: '1:246504429530:web:1afc90a5d1a2ce69e212e3',
    messagingSenderId: '246504429530',
    projectId: 'webnox-sprintly-55789',
    authDomain: 'webnox-sprintly-55789.firebaseapp.com',
    storageBucket: 'webnox-sprintly-55789.firebasestorage.app',
    measurementId: 'G-FFBRSN0BMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP3QXcwGVieCE8-Xo1h3U32Sg0dJ4hO8U',
    appId: '1:246504429530:android:1b3d1b8eafeeab87e212e3',
    messagingSenderId: '246504429530',
    projectId: 'webnox-sprintly-55789',
    storageBucket: 'webnox-sprintly-55789.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZkUFx3EBm-iYL9gcayZq4aZkxIwjfmUQ',
    appId: '1:246504429530:ios:8d92e2a77efccecfe212e3',
    messagingSenderId: '246504429530',
    projectId: 'webnox-sprintly-55789',
    storageBucket: 'webnox-sprintly-55789.firebasestorage.app',
    iosBundleId: 'com.webnox.webnoxTaskops',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZkUFx3EBm-iYL9gcayZq4aZkxIwjfmUQ',
    appId: '1:246504429530:ios:8d92e2a77efccecfe212e3',
    messagingSenderId: '246504429530',
    projectId: 'webnox-sprintly-55789',
    storageBucket: 'webnox-sprintly-55789.firebasestorage.app',
    iosBundleId: 'com.webnox.webnoxTaskops',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgwzTp5qH-iSVU3XK9tqGXt2DnjllDRes',
    appId: '1:246504429530:web:475606242864007ae212e3',
    messagingSenderId: '246504429530',
    projectId: 'webnox-sprintly-55789',
    authDomain: 'webnox-sprintly-55789.firebaseapp.com',
    storageBucket: 'webnox-sprintly-55789.firebasestorage.app',
    measurementId: 'G-M096PTXH31',
  );
}
